name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Docker Build
        run: |
          docker build -t todo-app-api .
          docker tag todo-app-api:latest <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/todo-app-api:latest

      - name: Docker Push
        run: |
          echo "${{ secrets.AWS_ECR_PASSWORD }}" | docker login -u AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com
          docker push <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/todo-app-api:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: todo-app-service
          cluster: todo-app-cluster
          wait-for-service-stability: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: <REGION>
